apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-demo-api
  release: dev
namespace: test   

resources:
- ../../base
images:
- name: demo
  newName: us-east-2.amazonaws.com/demo
  newTag: 

# patches:
#   - target:
#       kind: Ingress
#       name: demo-ingress
#     path: ingress-patch.json