apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: uat-
commonLabels:
  app: uat-demo-api
  release: uat
namespace: test
resources:
- ../../base

patchesStrategicMerge:
  - deployment.yaml
 
images:
- name: 
  newName: 
  newTag: 

patches:
  - target:
      kind: Ingress
      name: ingress
    path: ingress-patch.json