FROM node:14 AS build

WORKDIR /usr/src/app

COPY package*.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

FROM node:14-slim as production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/package*.json yarn.lock  ./
COPY --from=build /usr/src/app/node_modules ./node_modules

CMD [ "/bin/bash", "-c", "source /vault/secrets/config && yarn start" ]