apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-demo-app
  release: dev
namespace: test   #for rancher
# namespace: test 
resources:
- ../../base
images:
- name: demo
  newName: ecr.us-east-2.amazonaws.com/demo-app
  newTag: 

# patches:
#   - target:
#       kind: Ingress
#       name: demo-app-ingress
#     path: ingress-patch.json