apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deploy
  namespace: test
  labels:
    app: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'demo'
        vault.hashicorp.com/agent-inject-secret-config: 'dev/apps/demo'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "dev/apps/demo" -}}
            export Project="demo"
            export DB_PORT="{{ .Data.data.DB_PORT }}"
            export DB_HOST="{{ .Data.data.DB_HOST }}"
            export DB_NAME="{{ .Data.data.DB_NAME }}"
            export DB_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
            export DB_USER="{{ .Data.data.DB_USER }}"
          {{- end }}
# for without any template or default template
          # {{ with secret "dev/apps/jump" }}
          # {{ range $k, $v := .Data.data }}
          # export {{ $k }}="{{ $v }}"
          # {{ end }}
          # {{ end }} 
      name: demo
      labels:
        app: demo-api
    spec:
      imagePullSecrets:
      - name: regcred
      serviceAccountName: vault
      containers:
      - name: demo
        image: demo:v1.4
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        # envFrom:
        #   - configMapRef:
        #       name: envfilename
            

