apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: demo-api
namespace: test
resources:
  
  # - namespace.yaml
  - service.yaml
  - deployment.yaml
  # - ingress.yaml
